# This workflow will check code for code inconsistencies.

name: Blacken Code.
on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v2
      - uses: psf/black@master

      - name: Check formatting
        run: |
          python -m black . --diff --check
