# This workflow will check code for code inconsistencies.

name: Blacken Code.
on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@20.8b1
