name: Deploy

on:
  push:
  release:
    types: [released]

jobs:
  job:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install
      uses: snok/install-poetry@v1
      with:
        version: 1.2.0a2

    - name: Install Dependencies
      run: |
        poetry install --with docs

    - name: Build
      if: ${{ github.event_name == 'push' }}
      run: |
        poetry run python scripts/build_docs_for_publish.py
    - name: Build
      if: ${{ github.event_name == 'release' }}
      run: |
        poetry run python scripts/build_docs_for_publish.py --tag={{ github.event.release.tag_name }}

    - name: Push
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DOCS_TOKEN }}
        external_repository: steam-py/steam-py.github.io
        publish_branch: main
        publish_dir: docs
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
