# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package.

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

    - uses: snok/install-poetry@v1.1.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - uses: actions/cache@v2
      id: cached-dependecies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ matrix.python-version }}-no-dev

    - name: Validate pyproject.toml
      run: poetry check

    - name: Install dependencies
      if: steps.cached-dependecies.outputs.cache-hit != 'true'
      run: poetry install --no-dev

    - name: Publish to PyPI
      run: poetry publish --build --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
