name: Test.

on:
  issue_comment:
    types: [created]

jobs:
  testing:
    runs-on: ubuntu-latest

    - name: Run test
      if: github.event.issue.comment.body == "LGTM" && github.event.issue.comment.author == "Gobot1234"
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
          - name: Install dependencies
            run: pip install .[dev]
          - name: Run tests
            run: python3 tests
