name: Run tests.

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9.0-rc.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Run tests
      run: python3 tests -t
      env:
        USERNAME: ${{ secrets.STEAM_USERNAME }}
        PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        SHARED_SECRET: ${{ secrets.STEAM_SHARED_SECRET }}
        IDENTITY_SECRET: ${{ secrets.STEAM_IDENTITY_SECRET }}
