name: Run tests.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Validate pyproject.toml
        run: poetry check

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests for CPython ${{ matrix.python-version }}
        env:
          USERNAME: ${{ secrets.STEAM_USERNAME }}
          PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          SHARED_SECRET: ${{ secrets.STEAM_SHARED_SECRET }}
          IDENTITY_SECRET: ${{ secrets.STEAM_IDENTITY_SECRET }}
        run: poetry run pytest .
        timeout-minutes: 30
